### PR TITLE
Support for up to four images

### PR DESCRIPTION
**Pull request by MattJakeman**

### CODE REVIEW

**Comment by lluiscamino** [comment]
Thanks for contributing! 🙏  Adding support for more than one image is something that will definitely make the component better and more complete!

Only one issue: could you make it so that the images are passed as an array instead of as different properties?

I think a structure for the `config` object like the following would be better, but let me know what you think about it.
```javascript
const config = {
    ...,
    image: "", //  keep in order to support previous versions
    images: ["", "", "", ""], // up to 4 images
    ...
};
```

**Comment by MattJakeman** [comment]
Sure, that should be a pretty simple change. I'll try to take a look at it tomorrow.

**Comment by MattJakeman** [comment]
I've modified it slightly differently to your suggestion but so that it's still backwards compatible.

The `image` prop can now be either a single URL string, or an array of URL strings. It saved the need for any additional props doing it that way.

**Comment by lluiscamino** [comment]
Great! Thanks for your contribution :)

**Pull request merged**
